name: test-deployment

services:
  ingress:
    image: "traefik:v3.3"
    container_name: "ingress"
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure=true"  # trust X-Forwarded-* from LB
      - "--api=true"  # disable insecure dashboard for production
    ports:
      - "80:80"  # internal use behind the LB
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - internal

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - internal

networks:
  internal:
    driver: bridge
